export const projects = [
  {
    id: "1",
    name: "Ved Heights-20",
    location: "Mohanpura, Jaipur",
    address: "Plot No. / Khasra No. 231/8, Village - Mohanpura, Jaipur 302020 (Rajasthan)", // <-- Added
    overview:
      "Ved Heights-20 is a premium residential project located in the heart of Jaipur, offering luxurious 2 & 3 BHK apartments with modern amenities and stunning views. Experience the perfect blend of comfort and elegance in these thoughtfully designed homes, surrounded by lush greenery and convenient access to essential services.",
    stats: {
      Units: "42",  
      Area: null,
      Floors: "6",
      Type: "2 & 3 BHK Apartments",
      "Total Space": null,
      "Total Tower": "1",
      "Flat Sizes": "(984 sq.ft- 1560sq.ft)",
      "RERA No.": "RAJ/P/2025/3707",
    },
    amenities: [
      "24 X 7 Security",
      "Kids Play Area",
      "Landscape - Flower Garden",
      "Power Back Up",
      "Rain Water Harvesting",
      "Club House",
      "Gymnasium",
      "Terrace Garden",
      "Earthquake Resistant",
      "Visitor Parking",
      "Waste Disposal",
    ],
    mapEmbedUrl:
      "https://www.google.com/maps?q=26.828448575103195, 75.72902396442076&output=embed",
    connectivity: [
      "Well connected to major roads",
      "Close to public transport",
      "Proximity to schools and hospitals",
    ],
    gallery: [
      "/PropertyImages/vedheights20/vedheights20.jpg",
      "/PropertyImages/vedheights20/i1.png",
      "/PropertyImages/vedheights20/i2.png",
      "/PropertyImages/vedheights20/i3.png",
      "/PropertyImages/vedheights20/i4.png",
      "/PropertyImages/vedheights20/i5.png",
      "/PropertyImages/vedheights20/i6.png",
    ],
    layout: [
      "/PropertyImages/vedheights20/f1.png",
      "/PropertyImages/vedheights20/f2.png",
      // "/PropertyImages/vedheights20/f3.png",
    ],
    video: null,
    brochure: "/PropertyImages/vedheights20/brochure.pdf", 
  },
  {
    id: "9",
    name: "SB Heights-II",
    location: "Mansarover, Jaipur",
    address: "200 ft Road, Near Bharat Mata Circle, Mansarovar Extension, Jaipur", // <-- Added
    overview:
      "Introducing SB Heights II, our exquisite project of 54 premium 3, 4 & 5 BHK residential flats. Experience luxurious and comfortable living in the heart of the city, with meticulously designed spaces that cater to all your needs. Each apartment combines style and functionality, offering modern amenities for an elevated lifestyle. Discover the perfect blend of luxury and convenience at SB Heights II.",
    stats: {
      Units: "56",
      Area: " 500K.sq",
      Floors: "G+6",
      Type: "3/4/5 BHK",
      "Total Space": null,
      "Total Tower": "1",
      "Flat Sizes": "1445 SQ.FT-2203 SQ.FT",
      "RERA No.": "RAJ/P/2023/2742", 
    },
    amenities: [
      "mini theater",
      "Gymnasium",
      "Basement Parking",
      "Wi-Fi Enabled Campus",
      "Power Backup",
      "Elevator",
      "Kids Play Area",
      "Security Guard",
      "multipurpose Hall",
      "Library",
      "yoga and Meditation Area",
      "24/7 Water Supply",
      "Fire Safety Systems",
      "co-working space",
      "CCTV Surveillance",
    ],
    mapEmbedUrl:
      "https://www.google.com/maps?q=26.858228870831187, 75.73534226331914&output=embed",
    connectivity: [
      "9 min from Metro Station",
      "8 min from ISKCON Temple",
      "20 min from jaipur Airport",
      "Close to schools and hospitals",
    ],
    gallery: [
      "/PropertyImages/sbheights2/sb_heights.avif",
      "/PropertyImages/sbheights2/g2.jpg",
      "/PropertyImages/sbheights2/g3.jpg",
      "/PropertyImages/sbheights2/g4.jpg",
    ],
    layout: [
      "/PropertyImages/sbheights2/l1.png",
      "/PropertyImages/sbheights2/l2.png",
      "/PropertyImages/sbheights2/l3.png",
      "/PropertyImages/sbheights2/l4.png",
    ],
    video: null,
    brochure: "/PropertyImages/sbheights2/brochure.pdf",
  },
  {
    id: "2",
    name: "Sukriti Villa-II",
    location: "Patrakar Colony, Mansarover, Jaipur",
    address: " Opposite Choudhary Kanaram Paradise, Patrakar Colony, Mansarovar Extension, Jaipur", // <-- Added
    overview:
      "A premium residential project with all modern amenities and great connectivity. Elevate your living experience with exquisite flats, where luxury meets comfort. Elevate your living experience in our premium residential apartments where contemporary design meets comfort and functionality",
    stats: {
      Units: "7",
      Area: "",
      Floors: "2",
      Type: " 4 BHK villa",
      "Total Space": "",
      "Total Tower": "",
      "Flat Sizes": "2400",
      "RERA No.": "",
    },
    amenities: [
      "Vaastu Compliant",
      "Power Back Up",
      "Visitor Parking",
      "Power Backup",
      "Elevator",
      "Kids Play Area",
      "Rain Water Harvesting",
      "Seperate dressing areas",
      "Landscaped Garden",
      "Ultra luxurious drawing and dining set",
      "Super modular kitchen"
    ],
    mapEmbedUrl: "https://www.google.com/maps?q=26.833333304527255,75.73075403578538&output=embed",
    connectivity: [
      "5 min from Metro Station",
      "10 min from NH-8",
      "15 min from IGI Airport",
      "Close to schools and hospitals",
    ],
    gallery: [
      "/PropertyImages/sukritivilla2/sukritiVilla.png",
      "/PropertyImages/sukritivilla2/i1.JPG",
      "/PropertyImages/sukritivilla2/i2.JPG",
      "/PropertyImages/sukritivilla2/i3.JPG",
    ],
    layout: [
     null,
    ],
    video: null,
    brochure: null,
  },
  {
    id: "3",
    name: "Apna Ashiyana",
    location: "Near Urbana Jewels, Jaipur",
    address: "Near Urban Jewels, Kesar Chauraha, Mansarovar Extension, Jaipur", // <-- Added
    overview:
      "Triveni Builders & Developers presents a luxurious real estate project, Apna Aashiyana, in the pink city of Jaipur. Located at a prime location, this project offers beautifully designed 3BHK Villas and Houses with state of the art infrastructure. The ultra-modern facilities that make life comfortable and enjoyable. This project is close to markets, schools, hospitals, and ATMs. This is a ready to move residential project, and many lucky investors have already booked their dream villas. It is well-connected to the other parts of the city due to its proximity to Metro and the state highway. This is a RERA registered project.",
    stats: {
      Units: "107",
      Area: "2 Acres",
      Floors: "2",
      Type: "3 BHK villas",
      "Total Space": "",
      "Total Tower": "107",
      "Flat Sizes": "(65.03 - 83.61 sq.m)",
      "RERA No.": "",
    },
    amenities: [
      "24 X 7 Security",
      "Kids Play Area",
      "Landscape - Flower Garden",
      "Power Back Up",
      "Rain Water Harvesting",
      "School",
      "Vaastu Compliant",
      "Visitor Parking",
      "Waste Disposal",
    ],
    mapEmbedUrl: "https://www.google.com/maps?q=26.792759226000836,75.74846773973984&output=embed",
    connectivity: [
      "5 min from Metro Station",
      "10 min from NH-8",
      "15 min from IGI Airport",
      "Close to schools and hospitals",
    ],
    gallery: [
      "/PropertyImages/apnaashiyana/apnaashiyana.png",
      "/PropertyImages/apnaashiyana/i1.jpg",
      "/PropertyImages/apnaashiyana/i2.jpg",
      "/PropertyImages/apnaashiyana/i3.jpg",
      "/PropertyImages/apnaashiyana/i4.jpg",

    ],
    layout: [
   "/public/PropertyImages/apnaashiyana/f1.jpg",
    ],
    video: "https://www.youtube.com/embed/dQw4w9WgXcQ",
    brochure: "/brochures/sukriti_villa_brochure.pdf",
  },
  
  {
    id: "4",
    name: "Aarohi Dreams",
    location: "St. Willfered's College, Jaipur",
    address: "Aarohi Dreams, near St. Willfered's College, Jaipur, Rajasthan 302019", // <-- Added
    overview:
      "Aarohi Dreams in Mansarovar, Jaipur is a ready to move housing society. This project is a perfect combination of comfort and style, specifically designed to suit your requirements and conveniences. This housing society is now ready to be called home as families have started moving in. Check out some of the features of Aarohi Dreams housing society:",
    stats: {
      Units: "3",
      Area: "1,500 - 2,000 sq. ft.",
      Floors: "6",
      Type: "2 & 3 BHK Apartments",
      "Total Space": null,
      "Total Tower": "1",
      "Flat Sizes": "(139.35 - 185.81 sq.m)",
      "RERA No.": "",
    },
    amenities: [
      "24 X 7 Security",
      "Kids Play Area",
      "Landscape - Flower Garden",
      "Power Back Up",
      "Rain Water Harvesting",
      "Club House",
      "Gymnasium",
      "Terrace Garden",
      "Earthquake Resistant",
      "Visitor Parking",
      "Waste Disposal",
    ],
    mapEmbedUrl: "https://www.google.com/maps?q=26.8539,75.73538&output=embed",
    connectivity: [
      "2 min from ASI School",
      "5 min from st.willford's college",
      "15 min from IGI Airport",
      "Close to schools and hospitals",
    ],
    gallery: [
      "/PropertyImages/aarohidreams/aarohidreams.jpg",
      "/PropertyImages/aarohidreams/i1.jpg",
      "/PropertyImages/aarohidreams/i2.jpg",
      "/PropertyImages/aarohidreams/i3.jpg",
      "/PropertyImages/aarohidreams/i4.jpg",
    ],
    layout: [
      "/PropertyImages/aarohidreams/f1.jpg",
    ],
    video: null,
    brochure: "/PropertyImages/aarohidreams/AAROHIDREAMS.pdf",
  },
  {
    id: "5",
    name: "MB Heights-I",
    location: "Swarn Vihar, Jaipur",
    address: "MB Heights-I, Swarn Vihar, Jaipur, Rajasthan 302034", // <-- Added
    overview:
      "MB Heights-I is a premium residential project located in the heart of Jaipur, offering luxurious 3 BHK apartments with modern amenities and stunning views. Experience the perfect blend of comfort and elegance in these thoughtfully designed homes, surrounded by lush greenery and convenient access to essential services.",
    stats: {
      Units: "3",
      Area: "1,500 - 2,000 sq. ft.",
      Floors: "6",
      Type: "3 BHK Apartments",
      "Total Space": null,
      "Total Tower": "1",
      "Flat Sizes": "(139.35 - 185.81 sq.m)",
      "RERA No.": null,
    },
    amenities: [
      "24 X 7 Security",
      "Kids Play Area",
      "Landscape - Flower Garden",
      "Power Back Up",
      "Rain Water Harvesting",
      "Club House",
      "Gymnasium",
      "Terrace Garden",
      "Earthquake Resistant",
      "Visitor Parking",
      "Waste Disposal",
    ],
    mapEmbedUrl: "https://www.google.com/maps?q=26.808777186425527, 75.7532900288076&output=embed",
    connectivity: [
      "2 min from ASI School",
      "5 min from st.willford's college",
      "15 min from IGI Airport",
      "Close to schools and hospitals",
    ],
    gallery: [
      "/PropertyImages/mbheights1/mbheights1.jpg",
      "/PropertyImages/mbheights1/i1.jpg",
      "/PropertyImages/mbheights1/i2.jpg",
      "/PropertyImages/mbheights1/i3.jpg",
      "/PropertyImages/mbheights1/i4.jpg",
    ],
    layout: [
      "/PropertyImages/mbheights1/f1.jpg",
    ],
    video: "https://www.youtube.com/embed/dQw4w9WgXcQ",
    brochure: null,
  },
  {
    id: "6",
    name: "Ved Heights-18",
    location: "Tonk Road, Jaipur",
    address: "Ved Heights-18, Tonk Road, Jaipur, Rajasthan 302015", // <-- Added
    overview:
      "The luxurious experience begins the moment you step in Ved Heightsandyou instantly feel at home here, The apartments are made with sheer idea Ofcomfort and class. Right from the magnificent exteriors to mesmerizinginteriors, Ved Heights offers a life of extravagant luxury The building hasamazing amenities from air conditioned gymnasium to community hall forsocialization. The apartments also includes other fun facilities like gamesroom and full sized squash court which is a rarity in such societies.Surrounded with nature and peacq the apartments are a perfectblend of city life and nature. The apartments are situated at the primelocation of the city where one finds convenience and class atone place. It isindeed a place to live through the journey we call life in immense joy andContentment,",
    stats: {
      Units: "32",
      Area: "0.3 acre",
      Floors: "8",
      Type: "2 & 3 BHK Apartments",
      "Total Space": null,
      "Total Tower": "1",
      "Flat Sizes": "(909 sq.ft- 1215sq.ft)",
      "RERA No.": null,
    },
    amenities: [
      "24 X 7 Security",
      "Kids Play Area",
      "Landscape - Flower Garden",
      "Power Back Up",
      "Rain Water Harvesting",
      "Club House",
      "Gymnasium",
      "Terrace Garden",
      "Earthquake Resistant",
      "Visitor Parking",
      "Waste Disposal",
    ],
    mapEmbedUrl: "https://www.google.com/maps?q=26.834883441384964,75.74825720400153&output=embed",
    connectivity: [
      "10 min from raiwaly station",
      "5 min from hospital",
      "15 min from IGI Airport",
      "Close to schools and hospitals",
    ],
    gallery: [
      "/PropertyImages/vedheights18/vedheights18.png",
      "/PropertyImages/vedheights18/i1.avif",
      "/PropertyImages/vedheights18/i2.avif",
    ],
    layout: [
       "/PropertyImages/vedheights18/f1.png",
       "/PropertyImages/vedheights18/f2.png",
    ],
    video: null,
    brochure: "/PropertyImages/vedheights18/b1.pdf",
  },
  {
    id: "7",
    name: "Sukriti Villa-I",
    location: "Kia Homes, Jaipur",
    address: "Sukriti Villa-I, Kia Homes, Jaipur, Rajasthan 302020", // <-- Added
    overview:
      "Sukriti Villa-I is a premium residential project located in the heart of Jaipur, offering luxurious 4 BHK villas with modern amenities and stunning views. Experience the perfect blend of comfort and elegance in these thoughtfully designed homes, surrounded by lush greenery and convenient access to essential services.",
    stats: {
      Units: "4",
      Area: "1,500 - 2,000 sq. ft.",
      Floors: "2",
      Type: "3 BHK Villas",
      "Total Space": null,
      "Total Tower": "4",
      "Flat Sizes": "(139.35 - 185.81 sq.m)",
      "RERA No.": null,
    },
    amenities: [
      "Vaastu Compliant",
      "Power Back Up",
      "Visitor Parking",
      "Power Backup",
      "Elevator",
      "Kids Play Area",
      "Rain Water Harvesting",
      "Seperate dressing areas",
      "Landscaped Garden",
      "Ultra luxurious drawing and dining set",
      "Super modular kitchen"
    ],
    mapEmbedUrl: "https://www.google.com/maps?q=26.833333304527255,75.73075403578538&output=embed",
    connectivity: [
      "2 min from ASI School",  
      "5 min from st.willford's college",
      "15 min from IGI Airport",
      "Close to schools and hospitals",
    ],
    gallery: [
      "/PropertyImages/sukritivilla1/sukritivilla.png",
    ],
    layout: null,
    video: null,
    brochure: "/PropertyImages/sukritivilla1/brochure.pdf",
  },
  {
    id: "8",
    name: "vedheights-19",
    location: "Mansarovar, Jaipur",
    address: "Ved Heights-19, Mansarovar, Jaipur, Rajasthan 302020", // <-- Added
    overview:
      "The luxurious experience begins the moment you step in Ved Heights and you instantly feel at home here. The apartments are made with sheer idea ofcomfort and class. Right from the magnificent exteriors to mesmerizing interiors,Ved Heights offers a life of extravagant luxury.Surrounded with nature and peace, the apartments are a perfect blend ofcity life and nature. The apartments are situated at the prime location of the citywhere one finds convenience and class at one place. It is indeed a place to livethrough thejourneywe call life in immensejoy and contentment.",
    stats: {
      Units: "42",
      Area: "0.4 acre",
      Floors: "8",
      Type: "2, 3 & 4 BHK Apartments",
      "Total Space": null,
      "Total Tower": "1",
      "Flat Sizes": "(1000 sq.ft- 1650sq.ft)",
      "RERA No.": "RAJ/P/2022/2191",
    },
    amenities: [
       "24 X 7 Security",
      "Kids Play Area",
      "Landscape - Flower Garden",
      "Power Back Up",
      "Rain Water Harvesting",
      "Club House",
      "Gymnasium",
      "Terrace Garden",
      "Earthquake Resistant",
      "Visitor Parking",
      "Waste Disposal",
    ],
    mapEmbedUrl: "https://www.google.com/maps?q=26.834883441384964,75.74825720400153&output=embed",
    connectivity: [
      "10 min from IGM school",
      "5 min from CK birla hospital",
      "15 min from IGI Airport",
      "Close to schools and hospitals",
    ],
    gallery: [
      "/PropertyImages/vedheights19/vedheights19.png",
      "/PropertyImages/vedheights19/i1.png",
      "/PropertyImages/vedheights19/i2.png",
      "/PropertyImages/vedheights19/i3.png",
      "/PropertyImages/vedheights19/i4.png",
    ],
    layout: [
      "/PropertyImages/vedheights19/f1.png",
      "/PropertyImages/vedheights19/f2.png",
      "/PropertyImages/vedheights19/f3.png",
    ],
    video: null,
    brochure: "/PropertyImages/vedheights19/b2.pdf",
  }
];
