export const projects = [
  {
    id: "1",
    name: "SB Heights-II",
    location: "Mansarover, Jaipur",
    overview:
      "A premium residential project with all modern amenities and great connectivity.",
    stats: {
      Units: "56",
      Area: " 500K.sq",
      Floors: "G+6",
      Type: "3/4/5 BHK",
      "Total Space": "",
      "Total Tower": "1",
      "Flat Sizes": "",
      "RERA No.": "",
    },
    amenities: [
      "mini theater",
      "Gymnasium",
      "Basement Parking",
      "Wi-Fi Enabled Campus",
      "Power Backup",
      "Elevator",
      "Kids Play Area",
      "Security Guard",
      "multipurpose Hall",
      "Library",
      "yoga and Meditation Area",
      "24/7 Water Supply",
      "Fire Safety Systems",
      "co-working space",
      "CCTV Surveillance",
    ],
    mapEmbedUrl:
      "https://www.google.com/maps?q=26.858228870831187, 75.73534226331914&output=embed",
    connectivity: [
      "9 min from Metro Station",
      "8 min from ISKCON Temple",
      "20 min from jaipur Airport",
      "Close to schools and hospitals",
    ],
    gallery: [
      "../public/PropertyImages/sbheights2/sb_heights.avif",
      "../public/PropertyImages/sbheights2/g2.jpg",
      "../public/PropertyImages/sbheights2/g3.jpg",
      "../public/PropertyImages/sbheights2/g4.jpg",
    ],
    layout: [
      "../public/PropertyImages/sbheights2/l1.png",
      "../public/PropertyImages/sbheights2/l2.png",
      "../public/PropertyImages/sbheights2/l3.png",
      "../public/PropertyImages/sbheights2/l4.png",
    ],
    video: null,
    brochure: "../public/PropertyImages/sbheights2/brochure.pdf",
  },
  {
    id: "2",
    name: "Sukriti Vyas",
    location: "Mansarover, Jaipur",
    overview:
      "A premium residential project with all modern amenities and great connectivity. Elevate your living experience with exquisite flats, where luxury meets comfort. Elevate your living experience in our premium residential apartments where contemporary design meets comfort and functionality",
    stats: {
      Units: "200",
      Area: "       2 Acres",
      Floors: "10",
      Type: "3 BHK & 4 BHK",
      "Total Space": "",
      "Total Tower": "",
      "Flat Sizes": "",
      "RERA No.": "",
    },
    amenities: [
      "Swimming Pool",
      "Gymnasium",
      "Basement Parking",
      "Wi-Fi Enabled Campus",
      "Power Backup",
      "Elevator",
      "Kids Play Area",
      "Security Guard",
      "Laundry",
      "Landscaped Garden",
    ],
    mapEmbedUrl: "https://www.google.com/maps?q=26.8539,75.73538&output=embed",
    connectivity: [
      "5 min from Metro Station",
      "10 min from NH-8",
      "15 min from IGI Airport",
      "Close to schools and hospitals",
    ],
    gallery: [
      "../public/PropertyImages/sukritiVilla.png",
      "/images/gal2.jpg",
      "/images/gal3.jpg",
      "/images/gal4.jpg",
    ],
    layout: [
      "./public/PropertyImages/sbheights2/sb_heights.avif",
      "/images/gal2.jpg",
      "/images/gal3.jpg",
      "/images/gal4.jpg",
    ],
    video: "https://www.youtube.com/embed/dQw4w9WgXcQ",
    brochure: "../public/brochures/sukriti_vyas_brochure.pdf",
  },
  {
    id: "3",
    name: "Sukriti Villa",
    location: "Mansarover, Jaipur",
    overview:
      "A premium residential project with all modern amenities and great connectivity.",
    stats: {
      Units: "200",
      Area: "2 Acres",
      Floors: "10",
      Type: "3 BHK & 4 BHK",
      "Total Space": "",
      "Total Tower": "",
      "Flat Sizes": "",
      "RERA No.": "",
    },
    amenities: [
      "Swimming Pool",
      "Gymnasium",
      "Basement Parking",
      "Wi-Fi Enabled Campus",
      "Power Backup",
      "Elevator",
      "Kids Play Area",
      "Security Guard",
      "Laundry",
      "Landscaped Garden",
    ],
    mapEmbedUrl: "https://www.google.com/maps?q=26.8539,75.73538&output=embed",
    connectivity: [
      "5 min from Metro Station",
      "10 min from NH-8",
      "15 min from IGI Airport",
      "Close to schools and hospitals",
    ],
    gallery: [
      "../public/PropertyImages/sb_heights.avif",
      "/images/gal2.jpg",
      "/images/gal3.jpg",
      "/images/gal4.jpg",
    ],
    layout: [
      "/images/gal1.jpg",
      "/images/gal2.jpg",
      "/images/gal3.jpg",
      "/images/gal4.jpg",
    ],
    video: "https://www.youtube.com/embed/dQw4w9WgXcQ",
    brochure: "../public/brochures/sukriti_villa_brochure.pdf",
  },
  // Add more projects as needed
];
